version: "3.7"

services:
  salt-ssh:
    image: rpi-initial-salt-ssh
    build: .
    volumes:
      - type: bind
        source: ./etc/salt
        target: /etc/salt
      - type: bind
        source: ./files
        target: /opt/salt/files
      - type: bind
        source: ./srv
        target: /opt/salt/srv
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh
