version: "3.7"

services:
  salt-ssh:
    image: rpi-initial-salt-ssh
    build: .
    working_dir: /opt/salt
    volumes:
      - type: bind
        source: .
        target: /opt/salt
      - type: bind
        source: ./etc/salt
        target: /etc/salt
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh
